import { Inter } from "next/font/google";
import { Providers } from "@/providers";
import "./globals.scss";
import styles from "./layout.module.scss";
import Header from "@/core/common/Header";
import Footer from "@/core/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Snow Mouse Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <main className={styles.main}>
            <div className={styles.content}>
              <Header />
              {children}
            </div>
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
